import "./globals.css";
import styles from "./page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main}>
          <div className={styles.center}>
            <div className={styles.title}>Deposits</div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
